/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

//Importações da Biblioteca Java
import dao.GenericDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tabelas.Caminhos;
import tabelas.Campanhas;
import tabelas.Npcs;

/**
 *
 * @author Kaayo
 */
public class JFCaminhos extends javax.swing.JFrame {

    ArrayList arrayListMissoes = new ArrayList();//Criando ArrayList de nome 'arrayListMissoes'

    //Método Void para Centralziar o Formulário Caminhos quando iniciado (Visível)
    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    //Método void para Carregar o JComboBox Caminho
    public void carregaComboCampanha() throws SQLException, IllegalAccessException, NoSuchMethodException, IllegalArgumentException, InvocationTargetException, InstantiationException, ClassNotFoundException {

        //Criando Objetos
        GenericDAO gDAO = new GenericDAO();
        Campanhas campanhas = new Campanhas();

        //Criando Lista da Classe Campanhas
        List<Object> list = gDAO.listar(Campanhas.class);

        for (Object obj2 : list) {//criando 'For' para Lista os atributos da Classe Campanhas
            Campanhas c = (Campanhas) obj2;

            //Exibe Mensagem
            System.out.println("cod npc " + c.getCodigo_campanha());

            //Array recebe o Código e indexa-o
            arrayListMissoes.add(c.getCodigo_campanha());

            //JComboBox Missao recebe o nome da Campanha
            jcbMissao.addItem(c.getNome_campanha());
        }
    }
    /**
     * Creates new form JFCaminhos
     */
    public JFCaminhos() throws SQLException, IllegalAccessException, NoSuchMethodException, IllegalArgumentException, InvocationTargetException, InstantiationException, ClassNotFoundException {
        initComponents();
        centralizarComponente();
        carregaComboCampanha();//Inicia o método quando o JFCaminhos é iniciado
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfCaminho = new javax.swing.JTextField();
        jlCaminho = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jcbMissao = new javax.swing.JComboBox();
        jlCampanha = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtfCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCaminhoActionPerformed(evt);
            }
        });

        jlCaminho.setText("Nome Caminho");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jcbMissao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbMissaoItemStateChanged(evt);
            }
        });
        jcbMissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMissaoActionPerformed(evt);
            }
        });

        jlCampanha.setText("Selecionar Campanha");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCaminho)
                    .addComponent(jlCampanha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfCaminho)
                    .addComponent(jcbMissao, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCampanha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCaminho))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método Void presente no evento do Botão Salvar quando pressionado
    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        try {
            if (jtfCaminho.getText().equals("")) {//Se o Campo estiver em branco, faça...
                JOptionPane.showMessageDialog(null, "Por Favor insira um nome para o Caminho");//Exibe mensagem
            } else {//Senão faça...

                //Criando Objetos
                GenericDAO gDAO = new GenericDAO();
                Caminhos caminhos = new Caminhos();

                caminhos.setNome_caminho(jtfCaminho.getText());//Atributo 'nome_caminho' da Classe Caminhos recebe o dado inserido no campo JTextField
                caminhos.setCodigo_campanha((int) (arrayListMissoes.get(jcbMissao.getSelectedIndex()))); //apenas para teste               
                gDAO.adicionar(caminhos);//Cadastrando o Caminho no Banco de Dados***

                JOptionPane.showMessageDialog(null, "Caminho Cadastrado com Sucesso!");//Exibe Mensagem

                jtfCaminho.setText(""); //limpando campos apos cadastro
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFCaminhos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFCaminhos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(JFCaminhos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JFCaminhos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtfCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCaminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCaminhoActionPerformed

    private void jcbMissaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbMissaoItemStateChanged


    }//GEN-LAST:event_jcbMissaoItemStateChanged

    private void jcbMissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMissaoActionPerformed
        String t = (String.valueOf(jcbMissao.getSelectedIndex()) + jcbMissao.getSelectedItem().toString());//Variável 't' recebe o Código Index e o Nome do Atributo selecionado no JComboBox
        System.out.println(t);//Exibem os os dados que a variável tem armazenado
    }//GEN-LAST:event_jcbMissaoActionPerformed

    //Método void presente no evento do Botão Cancelar quando pressionado
    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jtfCaminho.setText("");//Limpa Campo
        this.dispose();//Fecha o Formulário      
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCaminhos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCaminhos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCaminhos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCaminhos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFCaminhos().setVisible(true);

                } catch (SQLException ex) {
                    Logger.getLogger(JFCaminhos.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(JFCaminhos.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (NoSuchMethodException ex) {
                    Logger.getLogger(JFCaminhos.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalArgumentException ex) {
                    Logger.getLogger(JFCaminhos.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (InvocationTargetException ex) {
                    Logger.getLogger(JFCaminhos.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(JFCaminhos.class
                            .getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JFCaminhos.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcbMissao;
    private javax.swing.JLabel jlCaminho;
    private javax.swing.JLabel jlCampanha;
    private javax.swing.JTextField jtfCaminho;
    // End of variables declaration//GEN-END:variables
}
