/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import com.sun.corba.se.impl.ior.NewObjectKeyTemplateBase;
import dao.GenericDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tabelas.Campanhas;

/**
 *
 * @author Orlando
 */
public class JFCampanhas extends javax.swing.JFrame {
    ArrayList arrayListCampanhas = new ArrayList();
    ArrayList arrayListTamX = new ArrayList();
    ArrayList arrayListTamY = new ArrayList();
    
    public void carregaComboCampanhas() throws SQLException, IllegalAccessException, NoSuchMethodException, IllegalArgumentException, InvocationTargetException, InstantiationException, ClassNotFoundException{
        GenericDAO genericDAO = new GenericDAO();
        List<Object> list = genericDAO.listar(Campanhas.class);
        
        for (Object obj: list) {
            Campanhas campanhas = (Campanhas) obj;
            arrayListCampanhas.add(campanhas.getCodigo_campanha());
            arrayListTamX.add(campanhas.getTam_x_campanha());
            arrayListTamY.add(campanhas.getTam_y_campanha());
            jcbCampanhas.addItem(campanhas.getNome_campanha());
        }
        
    }
    
    public void centralizarComponente() { 
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    
    /**
     * Creates new form JFCampanhas
     */
    public JFCampanhas() {
        initComponents();
        centralizarComponente();//Chama Método de Centralizar JFrame...
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpCadastrar = new javax.swing.JPanel();
        jtfNomeCampanha = new javax.swing.JTextField();
        jlCampanha = new javax.swing.JLabel();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlTamX = new javax.swing.JLabel();
        jlTamY = new javax.swing.JLabel();
        jtfTamX = new javax.swing.JTextField();
        jtfTamY = new javax.swing.JTextField();
        jpEditar = new javax.swing.JPanel();
        jcbCampanhas = new javax.swing.JComboBox();
        jlEditarNome = new javax.swing.JLabel();
        jtfEditarCampanha = new javax.swing.JTextField();
        jlEditarNomeCampanha = new javax.swing.JLabel();
        jbSalvarEdicao = new javax.swing.JButton();
        jbCancelarEdicao = new javax.swing.JButton();
        jtfEditarTamanhoX = new javax.swing.JTextField();
        jlEditarTamX = new javax.swing.JLabel();
        jlEditarTamY = new javax.swing.JLabel();
        jtfEditarTamanhoY = new javax.swing.JTextField();
        jtfInfo = new javax.swing.JLabel();
        jpExcluir = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Campanhas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtfNomeCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeCampanhaActionPerformed(evt);
            }
        });

        jlCampanha.setText("Nome Campanha");

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlTamX.setText("Tamanho mapa X");

        jlTamY.setText("Tamanho mapa Y");

        javax.swing.GroupLayout jpCadastrarLayout = new javax.swing.GroupLayout(jpCadastrar);
        jpCadastrar.setLayout(jpCadastrarLayout);
        jpCadastrarLayout.setHorizontalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastrarLayout.createSequentialGroup()
                        .addComponent(jlCampanha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNomeCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCadastrarLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpCadastrarLayout.createSequentialGroup()
                                .addComponent(jbCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCancelar))
                            .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpCadastrarLayout.createSequentialGroup()
                                    .addComponent(jlTamX)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfTamX, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpCadastrarLayout.createSequentialGroup()
                                    .addComponent(jlTamY)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfTamY, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jpCadastrarLayout.setVerticalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomeCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCampanha))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTamX)
                    .addComponent(jtfTamX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTamY)
                    .addComponent(jtfTamY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbCancelar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar", jpCadastrar);

        jcbCampanhas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCampanhasItemStateChanged(evt);
            }
        });
        jcbCampanhas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcbCampanhasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbCampanhasFocusLost(evt);
            }
        });
        jcbCampanhas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbCampanhasMouseClicked(evt);
            }
        });
        jcbCampanhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCampanhasActionPerformed(evt);
            }
        });

        jlEditarNome.setText("Selecione a Campanha");

        jtfEditarCampanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEditarCampanhaActionPerformed(evt);
            }
        });

        jlEditarNomeCampanha.setText("Novo nome");

        jbSalvarEdicao.setText("Salvar alterações");
        jbSalvarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarEdicaoActionPerformed(evt);
            }
        });

        jbCancelarEdicao.setText("Cancelar");
        jbCancelarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarEdicaoActionPerformed(evt);
            }
        });

        jtfEditarTamanhoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEditarTamanhoXActionPerformed(evt);
            }
        });

        jlEditarTamX.setText("Tamanho mapa X");

        jlEditarTamY.setText("Tamanho mapa Y");

        jtfEditarTamanhoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEditarTamanhoYActionPerformed(evt);
            }
        });

        jtfInfo.setText("*Alterar o tamanho do mapa da campanha, pode excluir caminhos*");

        javax.swing.GroupLayout jpEditarLayout = new javax.swing.GroupLayout(jpEditar);
        jpEditar.setLayout(jpEditarLayout);
        jpEditarLayout.setHorizontalGroup(
            jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarLayout.createSequentialGroup()
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEditarLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jbSalvarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelarEdicao))
                    .addGroup(jpEditarLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEditarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCampanhas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEditarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlEditarNomeCampanha)
                            .addComponent(jlEditarNome)))
                    .addGroup(jpEditarLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlEditarTamY)
                            .addComponent(jlEditarTamX))
                        .addGap(33, 33, 33)
                        .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEditarTamanhoX, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEditarTamanhoY, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jtfInfo)
                .addGap(21, 21, 21))
        );
        jpEditarLayout.setVerticalGroup(
            jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCampanhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEditarNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEditarCampanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEditarNomeCampanha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEditarTamX)
                    .addComponent(jtfEditarTamanhoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEditarTamanhoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEditarTamY))
                .addGap(18, 18, 18)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelarEdicao)
                    .addComponent(jbSalvarEdicao))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Editar", jpEditar);

        javax.swing.GroupLayout jpExcluirLayout = new javax.swing.GroupLayout(jpExcluir);
        jpExcluir.setLayout(jpExcluirLayout);
        jpExcluirLayout.setHorizontalGroup(
            jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
        jpExcluirLayout.setVerticalGroup(
            jpExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Excluir", jpExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeCampanhaActionPerformed

    }//GEN-LAST:event_jtfNomeCampanhaActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed

        try {
            //verifica se os campos estão vazios
            if (jtfNomeCampanha.getText().equals("") || (jtfTamX.getText().equals("")) || (jtfTamY.getText().equals(""))) { 
                JOptionPane.showMessageDialog(null, "Por favor insira todas as informações!"); 
            } else { 
                GenericDAO gDAO = new GenericDAO();
                Campanhas c = new Campanhas();
                
                c.setNome_campanha(jtfNomeCampanha.getText());
                c.setTam_x_campanha(Integer.parseInt(jtfTamX.getText()));
                c.setTam_y_campanha(Integer.parseInt(jtfTamY.getText()));
                gDAO.adicionar(c); //post
                
                JOptionPane.showMessageDialog(null, "Campanha " + jtfNomeCampanha.getText() + " foi cadastrada!");
                jtfNomeCampanha.setText(null);  //Limpa o Campos
                jtfTamX.setText(null);
                jtfTamY.setText(null);
            }
          
            arrayListCampanhas.clear();
            jcbCampanhas.removeAllItems();
            carregaComboCampanhas();
        
        } catch (SQLException ex) {//Caso Houver Exceção... E Não puder Cadastrar...
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        }//Fim Catch...
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jtfNomeCampanha.setText(null);  //Limpa o campo
        
        arrayListCampanhas.clear();
        arrayListTamX.clear();
        arrayListTamY.clear();
        jcbCampanhas.removeAllItems();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jcbCampanhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCampanhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCampanhasActionPerformed

    private void jtfEditarCampanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEditarCampanhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEditarCampanhaActionPerformed

    private void jbCancelarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarEdicaoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {/*
            // TODO add your handling code here:
            arrayListCampanhas.clear();
            jcbCampanhas.removeAll(); */
            
            carregaComboCampanhas();
        } catch (SQLException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jbSalvarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarEdicaoActionPerformed
        int cod = 0;
        cod = (int) arrayListCampanhas.get(jcbCampanhas.getSelectedIndex());
        try {
            Campanhas c = new Campanhas();
            GenericDAO gDAO = new GenericDAO();
            
            if (jtfEditarCampanha.getText().equals("") || (jtfEditarTamanhoX.getText().equals("")) || (jtfEditarTamanhoY.getText().equals(""))) { 
                JOptionPane.showMessageDialog(null, "Por favor insira todas as informações!"); 
            } else {
                c.setCodigo_campanha(cod);
                c.setNome_campanha(jtfEditarCampanha.getText());
                c.setTam_x_campanha(Integer.parseInt(jtfEditarTamanhoX.getText()));
                c.setTam_y_campanha(Integer.parseInt(jtfEditarTamanhoY.getText()));
            
                gDAO.alterar(c);
                
                JOptionPane.showMessageDialog(null, "Campanha "+ c.getNome_campanha() + " alterada com sucesso!");
                
                //limpando campos
                jtfEditarCampanha.setText(null);
                jtfEditarTamanhoX.setText(null);
                jtfEditarTamanhoY.setText(null);
                arrayListCampanhas.clear();
                arrayListTamX.clear();
                arrayListTamY.clear();
                jcbCampanhas.removeAllItems();
                carregaComboCampanhas();
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbSalvarEdicaoActionPerformed

    private void jtfEditarTamanhoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEditarTamanhoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEditarTamanhoYActionPerformed

    private void jtfEditarTamanhoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEditarTamanhoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEditarTamanhoXActionPerformed

    private void jcbCampanhasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbCampanhasFocusGained
        
    }//GEN-LAST:event_jcbCampanhasFocusGained

    private void jcbCampanhasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbCampanhasMouseClicked
        try {
            GenericDAO gDAO = new GenericDAO();
            Campanhas c = new Campanhas();
            
            jtfEditarCampanha.setText(null);
            jtfEditarTamanhoX.setText(null);
            jtfEditarTamanhoY.setText(null);
            jtfEditarCampanha.setText(jcbCampanhas.getItemAt(jcbCampanhas.getSelectedIndex()).toString());
            jtfEditarTamanhoX.setText(arrayListTamX.get(jcbCampanhas.getSelectedIndex()).toString());
            jtfEditarTamanhoY.setText(arrayListTamY.get(jcbCampanhas.getSelectedIndex()).toString());
            
        } catch (SQLException ex) {
            Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbCampanhasMouseClicked

    private void jcbCampanhasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbCampanhasFocusLost
        
    }//GEN-LAST:event_jcbCampanhasFocusLost

    private void jcbCampanhasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCampanhasItemStateChanged
        if (!arrayListCampanhas.isEmpty()) {
            try {
                GenericDAO gDAO = new GenericDAO();
                Campanhas c = new Campanhas();
            
                jtfEditarCampanha.setText(null);
                jtfEditarTamanhoX.setText(null);
                jtfEditarTamanhoY.setText(null);
                jtfEditarCampanha.setText(jcbCampanhas.getItemAt(jcbCampanhas.getSelectedIndex()).toString());
                jtfEditarTamanhoX.setText(arrayListTamX.get(jcbCampanhas.getSelectedIndex()).toString());
                jtfEditarTamanhoY.setText(arrayListTamY.get(jcbCampanhas.getSelectedIndex()).toString());
            
            } catch (SQLException ex) {
                Logger.getLogger(JFCampanhas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jcbCampanhasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCampanhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCampanhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCampanhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCampanhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCampanhas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelarEdicao;
    private javax.swing.JButton jbSalvarEdicao;
    private javax.swing.JComboBox jcbCampanhas;
    private javax.swing.JLabel jlCampanha;
    private javax.swing.JLabel jlEditarNome;
    private javax.swing.JLabel jlEditarNomeCampanha;
    private javax.swing.JLabel jlEditarTamX;
    private javax.swing.JLabel jlEditarTamY;
    private javax.swing.JLabel jlTamX;
    private javax.swing.JLabel jlTamY;
    private javax.swing.JPanel jpCadastrar;
    private javax.swing.JPanel jpEditar;
    private javax.swing.JPanel jpExcluir;
    private javax.swing.JTextField jtfEditarCampanha;
    private javax.swing.JTextField jtfEditarTamanhoX;
    private javax.swing.JTextField jtfEditarTamanhoY;
    private javax.swing.JLabel jtfInfo;
    private javax.swing.JTextField jtfNomeCampanha;
    private javax.swing.JTextField jtfTamX;
    private javax.swing.JTextField jtfTamY;
    // End of variables declaration//GEN-END:variables
}
