/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Tabelas.NpcsCombatentes;
import dao.GenericDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.lang.reflect.InvocationTargetException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tabelas.ArmadurasNpcs;
import tabelas.ArmasNpcs;
import tabelas.ConsumiveisNpcs;
import tabelas.EscudosNpcs;
import tabelas.Npcs;
import tabelas.NpcsFalas;

/**
 *
 * @author Micro7
 */
public class JFNpcAlterarExcluir extends javax.swing.JFrame {
         
    private Connection conexao;
    ArrayList arrayListNpc = new ArrayList();
    
    public void carregaComboNpcs() throws SQLException, IllegalAccessException, NoSuchMethodException, IllegalArgumentException, InvocationTargetException, InstantiationException, ClassNotFoundException {
        GenericDAO gDAO = new GenericDAO();
        Npcs exnpc = new Npcs();
        List<Object> list = gDAO.listar(Npcs.class);

        for (Object obj : list) {
            Npcs n = (Npcs) obj;

            //Arrays recebem os respectivos códigos e indexam-os
            arrayListNpc.add(n.getCodigo_npc());
            jCBExcluirNomeNpc.addItem(n.getNome_npc());
        }
}
    /**
     * Creates new form JFNpcAlterarExcluir
     */

    /**
     * Creates new form JFNpcAlterarExcluir
     * @throws java.sql.SQLException
     */

    /**
     * Creates new form JFNpcAlterarExcluir
     * @throws java.sql.SQLException
     * @throws java.lang.IllegalAccessException
     */

    /**
     * Creates new form JFNpcAlterarExcluir
     * @throws java.sql.SQLException
     * @throws java.lang.IllegalAccessException
     * @throws java.lang.NoSuchMethodException
     */

    /**
     * Creates new form JFNpcAlterarExcluir
     * @throws java.sql.SQLException
     * @throws java.lang.IllegalAccessException
     * @throws java.lang.NoSuchMethodException
     * @throws java.lang.reflect.InvocationTargetException
     */

    /**
     * Creates new form JFNpcAlterarExcluir
     * @throws java.sql.SQLException
     * @throws java.lang.IllegalAccessException
     * @throws java.lang.NoSuchMethodException
     * @throws java.lang.reflect.InvocationTargetException
     * @throws java.lang.ClassNotFoundException
     */

    /**
     * Creates new form JFNpcAlterarExcluir
     * @throws java.sql.SQLException
     * @throws java.lang.IllegalAccessException
     * @throws java.lang.NoSuchMethodException
     * @throws java.lang.reflect.InvocationTargetException
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     */    
    
    public JFNpcAlterarExcluir() throws SQLException, IllegalAccessException, NoSuchMethodException, IllegalArgumentException, InvocationTargetException, InstantiationException, ClassNotFoundException {
        initComponents();
        carregaComboNpcs();//Inicia o método
        centralizarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        LabelAlterarNomeNpc = new javax.swing.JLabel();
        LabelAlterarTipoNpc = new javax.swing.JLabel();
        JTFAlterarNomeNpc = new javax.swing.JTextField();
        LabelAlteracaoNpc = new javax.swing.JLabel();
        LabelAlterarDescricaoNpc = new javax.swing.JLabel();
        LabeAlterarlFala = new javax.swing.JLabel();
        LabelAlterarRespostaPositiva = new javax.swing.JLabel();
        LabelAlterarRespostaNegativa = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTAAlterarDescricaoNpc = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTAAlterarFalaNpc = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTAAlterarRespostaNegativa = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTAAlterarRespostaPositiva = new javax.swing.JTextArea();
        jBAlterarCadastrar = new javax.swing.JButton();
        jBAlterarAdicionarFala = new javax.swing.JButton();
        jCBAlterarTipoNpc = new javax.swing.JComboBox();
        jLAlterarAtributosNpc = new javax.swing.JLabel();
        jTFAlterarForca = new javax.swing.JTextField();
        jLAlterarForca = new javax.swing.JLabel();
        jLAlterarDestreza = new javax.swing.JLabel();
        jLAlterarConstituicao = new javax.swing.JLabel();
        jLAlterarInteligencia = new javax.swing.JLabel();
        jLAlterarSabedoria = new javax.swing.JLabel();
        jLAlterarFortitude = new javax.swing.JLabel();
        jLAlterarClassedeArmadura = new javax.swing.JLabel();
        jLAlterarBasedeAtaque = new javax.swing.JLabel();
        jLAlterarPontosdeVida = new javax.swing.JLabel();
        jLAlterarIniciativa = new javax.swing.JLabel();
        jLAlterarVontade = new javax.swing.JLabel();
        jLAlterarReflexos = new javax.swing.JLabel();
        jLAlterarCarisma = new javax.swing.JLabel();
        jTFAlterarDestreza = new javax.swing.JTextField();
        jTFAlterarConstituicao = new javax.swing.JTextField();
        jTFAlterarInteligencia = new javax.swing.JTextField();
        jTFAlterarSabedoria = new javax.swing.JTextField();
        jTFAlterarFortitude = new javax.swing.JTextField();
        jTFAlterarClassedeArmadura = new javax.swing.JTextField();
        jTFAlterarBasedeAtaque = new javax.swing.JTextField();
        jTFAlterarPontosdeVida = new javax.swing.JTextField();
        jTFAlterarIniciativa = new javax.swing.JTextField();
        jTFAlterarVontade = new javax.swing.JTextField();
        jTFAlterarReflexos = new javax.swing.JTextField();
        jTFAlterarCarisma = new javax.swing.JTextField();
        jLAlterarClasse = new javax.swing.JLabel();
        jLAlterarRaca = new javax.swing.JLabel();
        jCBAlterarRaca = new javax.swing.JComboBox();
        jCBAlterarClasse = new javax.swing.JComboBox();
        jLAlterarItens = new javax.swing.JLabel();
        jLAlterarArmaduraNpc = new javax.swing.JLabel();
        jLAlterarArmaNpc = new javax.swing.JLabel();
        jLAlterarConsumivelNpc = new javax.swing.JLabel();
        jLAlterarEscudoNpc = new javax.swing.JLabel();
        jCBAlterarArmaduraNpc = new javax.swing.JComboBox();
        jCBAlterarArmaNpc = new javax.swing.JComboBox();
        jCBAlterarConsumivelNpc = new javax.swing.JComboBox();
        jCBAlterarEscudoNpc = new javax.swing.JComboBox();
        jTFAlterarQuantidadeArmaduraNpc = new javax.swing.JTextField();
        jTFAlterarQuantidadeArmaNpc = new javax.swing.JTextField();
        jTFAlterarQuantidadeConsumivelNpc = new javax.swing.JTextField();
        jTFAlterarQuantidadeEscudoNpc = new javax.swing.JTextField();
        jTFAlterarCodigoNpc = new javax.swing.JTextField();
        jTFAlterarCodArmadura = new javax.swing.JTextField();
        jLAlterarQuantidadeItensNpc = new javax.swing.JLabel();
        jTFAlterarCodArma = new javax.swing.JTextField();
        jTFAlterarCodConsumivel = new javax.swing.JTextField();
        jTFAlterarCodEscudo = new javax.swing.JTextField();
        jTFAlterarCodRaca = new javax.swing.JTextField();
        jTFAlterarCodClasse = new javax.swing.JTextField();
        jBAlterarAdicionarItenNpc = new javax.swing.JButton();
        jPExcluir = new javax.swing.JPanel();
        LabelExcluirNomeNpc = new javax.swing.JLabel();
        LabelExcluirNpc = new javax.swing.JLabel();
        jCBExcluirNomeNpc = new javax.swing.JComboBox();
        jBExcluirNpc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelAlterarNomeNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAlterarNomeNpc.setText("Nome:");
        jPanel1.add(LabelAlterarNomeNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 45, -1));

        LabelAlterarTipoNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAlterarTipoNpc.setText("Tipo:");
        jPanel1.add(LabelAlterarTipoNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, 45, -1));

        JTFAlterarNomeNpc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(JTFAlterarNomeNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 47, 155, -1));

        LabelAlteracaoNpc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelAlteracaoNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAlteracaoNpc.setText("Alteração de Npc's");
        LabelAlteracaoNpc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LabelAlteracaoNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 170, 28));

        LabelAlterarDescricaoNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAlterarDescricaoNpc.setText("Descrição Npc:");
        jPanel1.add(LabelAlterarDescricaoNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 111, 375, -1));

        LabeAlterarlFala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabeAlterarlFala.setText("Fala:");
        LabeAlterarlFala.setPreferredSize(new java.awt.Dimension(84, 14));
        jPanel1.add(LabeAlterarlFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 233, 375, -1));

        LabelAlterarRespostaPositiva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAlterarRespostaPositiva.setText("Resposta Positiva:");
        jPanel1.add(LabelAlterarRespostaPositiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 355, 375, -1));

        LabelAlterarRespostaNegativa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAlterarRespostaNegativa.setText("Resposta Negativa:");
        jPanel1.add(LabelAlterarRespostaNegativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 477, 375, -1));

        jTAAlterarDescricaoNpc.setColumns(20);
        jTAAlterarDescricaoNpc.setLineWrap(true);
        jTAAlterarDescricaoNpc.setRows(5);
        jTAAlterarDescricaoNpc.setPreferredSize(null);
        jScrollPane9.setViewportView(jTAAlterarDescricaoNpc);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 131, 375, -1));

        jTAAlterarFalaNpc.setColumns(20);
        jTAAlterarFalaNpc.setLineWrap(true);
        jTAAlterarFalaNpc.setRows(5);
        jTAAlterarFalaNpc.setPreferredSize(null);
        jScrollPane10.setViewportView(jTAAlterarFalaNpc);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 253, 375, -1));

        jTAAlterarRespostaNegativa.setColumns(20);
        jTAAlterarRespostaNegativa.setLineWrap(true);
        jTAAlterarRespostaNegativa.setRows(5);
        jTAAlterarRespostaNegativa.setPreferredSize(null);
        jScrollPane11.setViewportView(jTAAlterarRespostaNegativa);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 497, 375, -1));

        jTAAlterarRespostaPositiva.setColumns(20);
        jTAAlterarRespostaPositiva.setLineWrap(true);
        jTAAlterarRespostaPositiva.setRows(5);
        jTAAlterarRespostaPositiva.setPreferredSize(null);
        jScrollPane12.setViewportView(jTAAlterarRespostaPositiva);

        jPanel1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 375, 375, -1));

        jBAlterarCadastrar.setText("Cadastrar");
        jPanel1.add(jBAlterarCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 604, 120, 30));

        jBAlterarAdicionarFala.setText("Adicionar Fala");
        jPanel1.add(jBAlterarAdicionarFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 604, 120, 30));

        jCBAlterarTipoNpc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Combatente", "Comerciante", "Guia", "Missão", "Coletável" }));
        jCBAlterarTipoNpc.setSelectedIndex(-1);
        jPanel1.add(jCBAlterarTipoNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 77, 155, -1));

        jLAlterarAtributosNpc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLAlterarAtributosNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarAtributosNpc.setText("Atributos NPC");
        jPanel1.add(jLAlterarAtributosNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 73, 214, -1));

        jTFAlterarForca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFAlterarForca.setName(""); // NOI18N
        jPanel1.add(jTFAlterarForca, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 193, 90, -1));

        jLAlterarForca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarForca.setText("Força:");
        jPanel1.add(jLAlterarForca, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 196, 120, -1));

        jLAlterarDestreza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarDestreza.setText("Destreza:");
        jPanel1.add(jLAlterarDestreza, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 222, 120, -1));

        jLAlterarConstituicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarConstituicao.setText("Constituição:");
        jPanel1.add(jLAlterarConstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 248, 120, -1));

        jLAlterarInteligencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarInteligencia.setText("Inteligência:");
        jPanel1.add(jLAlterarInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 274, 120, -1));

        jLAlterarSabedoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarSabedoria.setText("Sabedoria:");
        jPanel1.add(jLAlterarSabedoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 300, 120, -1));

        jLAlterarFortitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarFortitude.setText("Fortitude:");
        jPanel1.add(jLAlterarFortitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 326, 120, -1));

        jLAlterarClassedeArmadura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarClassedeArmadura.setText("Classe de Armadura:");
        jPanel1.add(jLAlterarClassedeArmadura, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 352, 120, -1));

        jLAlterarBasedeAtaque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarBasedeAtaque.setText("Base de Ataque:");
        jPanel1.add(jLAlterarBasedeAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 378, 120, -1));

        jLAlterarPontosdeVida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarPontosdeVida.setText("Pontos de Vida:");
        jPanel1.add(jLAlterarPontosdeVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 404, 120, -1));

        jLAlterarIniciativa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarIniciativa.setText("Iniciativa:");
        jPanel1.add(jLAlterarIniciativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 430, 120, -1));

        jLAlterarVontade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarVontade.setText("Vontade:");
        jPanel1.add(jLAlterarVontade, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 456, 120, -1));

        jLAlterarReflexos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarReflexos.setText("Reflexos:");
        jPanel1.add(jLAlterarReflexos, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 482, 120, -1));

        jLAlterarCarisma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarCarisma.setText("Carisma:");
        jPanel1.add(jLAlterarCarisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 508, 120, -1));

        jTFAlterarDestreza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFAlterarDestreza.setName(""); // NOI18N
        jPanel1.add(jTFAlterarDestreza, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 219, 90, -1));

        jTFAlterarConstituicao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarConstituicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 245, 90, -1));

        jTFAlterarInteligencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 271, 90, -1));

        jTFAlterarSabedoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarSabedoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 297, 90, -1));

        jTFAlterarFortitude.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarFortitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 323, 90, -1));

        jTFAlterarClassedeArmadura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarClassedeArmadura, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 349, 90, -1));

        jTFAlterarBasedeAtaque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarBasedeAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 375, 90, -1));

        jTFAlterarPontosdeVida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarPontosdeVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 401, 90, -1));

        jTFAlterarIniciativa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarIniciativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 427, 90, -1));

        jTFAlterarVontade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarVontade, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 453, 90, -1));

        jTFAlterarReflexos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarReflexos, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 479, 90, -1));

        jTFAlterarCarisma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarCarisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 505, 90, -1));

        jLAlterarClasse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarClasse.setText("Classe:");
        jPanel1.add(jLAlterarClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 147, 214, -1));

        jLAlterarRaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarRaca.setText("Raça:");
        jPanel1.add(jLAlterarRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 101, 214, -1));

        jPanel1.add(jCBAlterarRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 121, 214, -1));

        jPanel1.add(jCBAlterarClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 167, 214, -1));

        jLAlterarItens.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLAlterarItens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarItens.setText("Itens NPC");
        jPanel1.add(jLAlterarItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 73, 155, -1));

        jLAlterarArmaduraNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarArmaduraNpc.setText("Armadura:");
        jPanel1.add(jLAlterarArmaduraNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 101, 155, -1));

        jLAlterarArmaNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarArmaNpc.setText("Arma:");
        jPanel1.add(jLAlterarArmaNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 147, 155, -1));

        jLAlterarConsumivelNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarConsumivelNpc.setText("Consumivel:");
        jPanel1.add(jLAlterarConsumivelNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 193, 155, -1));

        jLAlterarEscudoNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarEscudoNpc.setText("Escudo:");
        jPanel1.add(jLAlterarEscudoNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 239, 155, -1));

        jPanel1.add(jCBAlterarArmaduraNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 121, 155, -1));

        jPanel1.add(jCBAlterarArmaNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 167, 155, -1));

        jPanel1.add(jCBAlterarConsumivelNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 213, 155, -1));

        jPanel1.add(jCBAlterarEscudoNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 259, 155, -1));

        jTFAlterarQuantidadeArmaduraNpc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarQuantidadeArmaduraNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 121, 45, -1));

        jTFAlterarQuantidadeArmaNpc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarQuantidadeArmaNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 167, 45, -1));

        jTFAlterarQuantidadeConsumivelNpc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarQuantidadeConsumivelNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 213, 45, -1));

        jTFAlterarQuantidadeEscudoNpc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarQuantidadeEscudoNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 259, 45, -1));

        jTFAlterarCodigoNpc.setEditable(false);
        jTFAlterarCodigoNpc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarCodigoNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 47, 30, -1));

        jTFAlterarCodArmadura.setEditable(false);
        jTFAlterarCodArmadura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarCodArmadura, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 121, 30, -1));

        jLAlterarQuantidadeItensNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlterarQuantidadeItensNpc.setText("Qtd:");
        jPanel1.add(jLAlterarQuantidadeItensNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 101, 45, -1));

        jTFAlterarCodArma.setEditable(false);
        jTFAlterarCodArma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarCodArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 167, 30, -1));

        jTFAlterarCodConsumivel.setEditable(false);
        jTFAlterarCodConsumivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarCodConsumivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 213, 30, -1));

        jTFAlterarCodEscudo.setEditable(false);
        jTFAlterarCodEscudo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarCodEscudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 259, 31, -1));

        jTFAlterarCodRaca.setEditable(false);
        jTFAlterarCodRaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarCodRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 121, 30, -1));

        jTFAlterarCodClasse.setEditable(false);
        jTFAlterarCodClasse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTFAlterarCodClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 167, 30, -1));

        jBAlterarAdicionarItenNpc.setText("Adicionar Itens");
        jPanel1.add(jBAlterarAdicionarItenNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 297, 155, -1));

        jTabbedPane1.addTab("Alterar", jPanel1);

        jPExcluir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPExcluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelExcluirNomeNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelExcluirNomeNpc.setText("Nome:");
        jPExcluir.add(LabelExcluirNomeNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 155, -1));

        LabelExcluirNpc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelExcluirNpc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelExcluirNpc.setText("Excluir Npc's");
        LabelExcluirNpc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPExcluir.add(LabelExcluirNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 120, 28));

        jPExcluir.add(jCBExcluirNomeNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, 155, -1));

        jBExcluirNpc.setText("EXCLUIR");
        jBExcluirNpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirNpcActionPerformed(evt);
            }
        });
        jPExcluir.add(jBExcluirNpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 108, 155, -1));

        jTabbedPane1.addTab("Excluir", jPExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void centralizarComponente() {

        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
        
    }
    
    private void jBExcluirNpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirNpcActionPerformed
        // TODO add your handling code here:
        try {
            GenericDAO gDAO = new GenericDAO();
            Npcs npc = new Npcs();
            ArmadurasNpcs durasNpc = new ArmadurasNpcs();
            ArmasNpcs armaNpc = new ArmasNpcs();
            EscudosNpcs escudoNpc = new EscudosNpcs();
            ConsumiveisNpcs consuNpc = new ConsumiveisNpcs();
            NpcsCombatentes combateNpc = new NpcsCombatentes();
            NpcsFalas falaNpc = new NpcsFalas();
          
            //Busca o codigo do npc na tabela Armadurasnpc e exclui ambos (npc e o codigo do armadura que esta o npc).
            durasNpc.setCodigo_npc((int) arrayListNpc.get(jCBExcluirNomeNpc.getSelectedIndex()));
            gDAO.excluir(durasNpc);
            
            //Busca o codigo do npc na tabela ArmasNpcs e exclui ambos (npc e o codigo do armas que esta o npc).
            armaNpc.setCodigo_npc((int) arrayListNpc.get(jCBExcluirNomeNpc.getSelectedIndex()));
            gDAO.excluir(armaNpc);
            
            //Busca o codigo do npc na tabela ArmasNpcs e exclui ambos (npc e o codigo do armas que esta o npc).
            escudoNpc.setCodigo_npc((int) arrayListNpc.get(jCBExcluirNomeNpc.getSelectedIndex()));
            gDAO.excluir(escudoNpc);
            
            //Busca o codigo do npc na tabela consumiveisnpc e exclui ambos (npc e o codigo do consumivel que esta o npc).
            consuNpc.setCodigo_npc((int) arrayListNpc.get(jCBExcluirNomeNpc.getSelectedIndex()));
            gDAO.excluir(consuNpc);
            
            //Busca o codigo do npc na tabela Npccombatente e exclui ambos (npc e o codigo do npc combatente que esta o npc).
            combateNpc.setCodigo_npc((int) arrayListNpc.get(jCBExcluirNomeNpc.getSelectedIndex()));
            gDAO.excluir(combateNpc);
            
            //Busca o codigo do npc na tabela Npccombatente e exclui ambos (npc e o codigo do npc combatente que esta o codigo do npc).
            falaNpc.setCodigo_npc((int) arrayListNpc.get(jCBExcluirNomeNpc.getSelectedIndex()));
            gDAO.excluir(falaNpc);
            
            //Busca o codigo do npc na tabela Npc e exclui o mesmo.
            npc.setCodigo_npc((int) arrayListNpc.get(jCBExcluirNomeNpc.getSelectedIndex()));
            gDAO.excluir(npc);
            arrayListNpc.clear();
            jCBExcluirNomeNpc.removeAllItems();
            JOptionPane.showMessageDialog(null, "Npc Excluido com sucesso!");
            carregaComboNpcs();
            
            } catch (SQLException ex) {
            Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchFieldException ex) {
            Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBExcluirNpcActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFNpcAlterarExcluir().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoSuchMethodException ex) {
                    Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalArgumentException ex) {
                    Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvocationTargetException ex) {
                    Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JFNpcAlterarExcluir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFAlterarNomeNpc;
    private javax.swing.JLabel LabeAlterarlFala;
    private javax.swing.JLabel LabelAlteracaoNpc;
    private javax.swing.JLabel LabelAlterarDescricaoNpc;
    private javax.swing.JLabel LabelAlterarNomeNpc;
    private javax.swing.JLabel LabelAlterarRespostaNegativa;
    private javax.swing.JLabel LabelAlterarRespostaPositiva;
    private javax.swing.JLabel LabelAlterarTipoNpc;
    private javax.swing.JLabel LabelExcluirNomeNpc;
    private javax.swing.JLabel LabelExcluirNpc;
    private javax.swing.JButton jBAlterarAdicionarFala;
    private javax.swing.JButton jBAlterarAdicionarItenNpc;
    private javax.swing.JButton jBAlterarCadastrar;
    private javax.swing.JButton jBExcluirNpc;
    private javax.swing.JComboBox jCBAlterarArmaNpc;
    private javax.swing.JComboBox jCBAlterarArmaduraNpc;
    private javax.swing.JComboBox jCBAlterarClasse;
    private javax.swing.JComboBox jCBAlterarConsumivelNpc;
    private javax.swing.JComboBox jCBAlterarEscudoNpc;
    private javax.swing.JComboBox jCBAlterarRaca;
    private javax.swing.JComboBox jCBAlterarTipoNpc;
    private javax.swing.JComboBox jCBExcluirNomeNpc;
    private javax.swing.JLabel jLAlterarArmaNpc;
    private javax.swing.JLabel jLAlterarArmaduraNpc;
    private javax.swing.JLabel jLAlterarAtributosNpc;
    private javax.swing.JLabel jLAlterarBasedeAtaque;
    private javax.swing.JLabel jLAlterarCarisma;
    private javax.swing.JLabel jLAlterarClasse;
    private javax.swing.JLabel jLAlterarClassedeArmadura;
    private javax.swing.JLabel jLAlterarConstituicao;
    private javax.swing.JLabel jLAlterarConsumivelNpc;
    private javax.swing.JLabel jLAlterarDestreza;
    private javax.swing.JLabel jLAlterarEscudoNpc;
    private javax.swing.JLabel jLAlterarForca;
    private javax.swing.JLabel jLAlterarFortitude;
    private javax.swing.JLabel jLAlterarIniciativa;
    private javax.swing.JLabel jLAlterarInteligencia;
    private javax.swing.JLabel jLAlterarItens;
    private javax.swing.JLabel jLAlterarPontosdeVida;
    private javax.swing.JLabel jLAlterarQuantidadeItensNpc;
    private javax.swing.JLabel jLAlterarRaca;
    private javax.swing.JLabel jLAlterarReflexos;
    private javax.swing.JLabel jLAlterarSabedoria;
    private javax.swing.JLabel jLAlterarVontade;
    private javax.swing.JPanel jPExcluir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTAAlterarDescricaoNpc;
    private javax.swing.JTextArea jTAAlterarFalaNpc;
    private javax.swing.JTextArea jTAAlterarRespostaNegativa;
    private javax.swing.JTextArea jTAAlterarRespostaPositiva;
    private javax.swing.JTextField jTFAlterarBasedeAtaque;
    private javax.swing.JTextField jTFAlterarCarisma;
    private javax.swing.JTextField jTFAlterarClassedeArmadura;
    private javax.swing.JTextField jTFAlterarCodArma;
    private javax.swing.JTextField jTFAlterarCodArmadura;
    private javax.swing.JTextField jTFAlterarCodClasse;
    private javax.swing.JTextField jTFAlterarCodConsumivel;
    private javax.swing.JTextField jTFAlterarCodEscudo;
    private javax.swing.JTextField jTFAlterarCodRaca;
    private javax.swing.JTextField jTFAlterarCodigoNpc;
    private javax.swing.JTextField jTFAlterarConstituicao;
    private javax.swing.JTextField jTFAlterarDestreza;
    private javax.swing.JTextField jTFAlterarForca;
    private javax.swing.JTextField jTFAlterarFortitude;
    private javax.swing.JTextField jTFAlterarIniciativa;
    private javax.swing.JTextField jTFAlterarInteligencia;
    private javax.swing.JTextField jTFAlterarPontosdeVida;
    private javax.swing.JTextField jTFAlterarQuantidadeArmaNpc;
    private javax.swing.JTextField jTFAlterarQuantidadeArmaduraNpc;
    private javax.swing.JTextField jTFAlterarQuantidadeConsumivelNpc;
    private javax.swing.JTextField jTFAlterarQuantidadeEscudoNpc;
    private javax.swing.JTextField jTFAlterarReflexos;
    private javax.swing.JTextField jTFAlterarSabedoria;
    private javax.swing.JTextField jTFAlterarVontade;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
