/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexao.Conexao;
import dao.GenericDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import tabelas.PersonagensArmaduras;
import tabelas.PersonagensArmas;
import tabelas.PersonagensConsumiveis;
import tabelas.PersonagensEscudos;

/**
 *
 * @author Micro10
 */
public class JFVendaItens extends javax.swing.JFrame {

    /**
     * Creates new form JFVendaItens
     */
    
     public void centralizarComponente() {
        
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation ((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
     
    public JFVendaItens() {
        initComponents();
        centralizarComponente();
        jbComprar.setVisible(false);
        lbComprar.setVisible(false);
        lbPrecoComprar.setVisible(false);
        jcbVenderConsumiveis.setVisible(false);
        jcbVenderEscudos.setVisible(false);
        jcbVenderArmaduras.setVisible(false);
        jcbVenderArmas.setVisible(false);
        jcVenderConsumiveis.setVisible(false);
        jcVenderEscudos.setVisible(false);
        jcVenderArmaduras.setVisible(false);         //////Oculta objetos setados antes de abrir o form
        jcVenderArmas.setVisible(false);
        jlQuantComprar.setVisible(false);
        jlQuantVender.setVisible(false);
        QuantComprar.setVisible(false);
        QuantVender.setVisible(false);

        jbVender.setVisible(false);
        lbVender.setVisible(false);
        lbPreçoVender.setVisible(false);
        jcbComprarConsumiveis.setVisible(false);
        jcbComprarEscudos.setVisible(false);
        jcbComprarArmaduras.setVisible(false);
        jcbComprarArmas.setVisible(false);
        jcComprarConsumiveis.setVisible(false);
        jcComprarEscudos.setVisible(false);
        jcComprarArmaduras.setVisible(false);
        jcComprarArmas.setVisible(false);
        
        
        
        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        label2 = new java.awt.Label();
        lbDinheiroPersonagem = new java.awt.Label();
        lbComprar = new java.awt.Label();
        jcComprarArmas = new javax.swing.JComboBox();
        lbVender = new java.awt.Label();
        jcVenderArmas = new javax.swing.JComboBox();
        jcComprarArmaduras = new javax.swing.JComboBox();
        jcComprarEscudos = new javax.swing.JComboBox();
        jcComprarConsumiveis = new javax.swing.JComboBox();
        jcVenderArmaduras = new javax.swing.JComboBox();
        jcVenderEscudos = new javax.swing.JComboBox();
        jcVenderConsumiveis = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lbPrecoComprar = new java.awt.Label();
        lbPreçoVender = new java.awt.Label();
        jbComprar = new javax.swing.JButton();
        jbVender = new javax.swing.JButton();
        jcbComprar = new javax.swing.JCheckBox();
        jcbVender = new javax.swing.JCheckBox();
        jcbComprarArmas = new javax.swing.JCheckBox();
        jcbComprarArmaduras = new javax.swing.JCheckBox();
        jcbComprarEscudos = new javax.swing.JCheckBox();
        jcbComprarConsumiveis = new javax.swing.JCheckBox();
        jcbVenderArmas = new javax.swing.JCheckBox();
        jcbVenderArmaduras = new javax.swing.JCheckBox();
        jcbVenderEscudos = new javax.swing.JCheckBox();
        jcbVenderConsumiveis = new javax.swing.JCheckBox();
        jlQuantComprar = new javax.swing.JLabel();
        jlQuantVender = new javax.swing.JLabel();
        QuantComprar = new javax.swing.JTextField();
        QuantVender = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Peças de Ouro Disponiveis:");

        lbComprar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbComprar.setText("O que você deseja comprar?");

        jcComprarArmas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcComprarArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcComprarArmasActionPerformed(evt);
            }
        });

        lbVender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbVender.setText("O que você deseja vender?");

        jcVenderArmas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcComprarEscudos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcComprarConsumiveis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcVenderArmaduras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcVenderEscudos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcVenderConsumiveis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("Olá viajante você deseja comprar ou vender itens?");

        lbPrecoComprar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPrecoComprar.setText("Preço:");

        lbPreçoVender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPreçoVender.setText("Preço:");

        jbComprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbComprar.setText("Comprar");
        jbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprarActionPerformed(evt);
            }
        });

        jbVender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbVender.setText("Vender");
        jbVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVenderActionPerformed(evt);
            }
        });

        jcbComprar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprar.setText("Comprar");
        jcbComprar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jcbComprarComponentHidden(evt);
            }
        });
        jcbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarActionPerformed(evt);
            }
        });

        jcbVender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVender.setText("Vender");
        jcbVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderActionPerformed(evt);
            }
        });

        jcbComprarArmas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarArmas.setText("Armas");
        jcbComprarArmas.setHideActionText(true);
        jcbComprarArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarArmasActionPerformed(evt);
            }
        });

        jcbComprarArmaduras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarArmaduras.setText("Armaduras");
        jcbComprarArmaduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarArmadurasActionPerformed(evt);
            }
        });

        jcbComprarEscudos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarEscudos.setText("Escudos");
        jcbComprarEscudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarEscudosActionPerformed(evt);
            }
        });

        jcbComprarConsumiveis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarConsumiveis.setText("Consumiveis");
        jcbComprarConsumiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarConsumiveisActionPerformed(evt);
            }
        });

        jcbVenderArmas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderArmas.setText("Armas");
        jcbVenderArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderArmasActionPerformed(evt);
            }
        });

        jcbVenderArmaduras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderArmaduras.setText("Armaduras");
        jcbVenderArmaduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderArmadurasActionPerformed(evt);
            }
        });

        jcbVenderEscudos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderEscudos.setText("Escudos");
        jcbVenderEscudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderEscudosActionPerformed(evt);
            }
        });

        jcbVenderConsumiveis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderConsumiveis.setText("Consumiveis");
        jcbVenderConsumiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderConsumiveisActionPerformed(evt);
            }
        });

        jlQuantComprar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlQuantComprar.setText("Quantidade:");

        jlQuantVender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlQuantVender.setText("Quantidade:");

        QuantComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbDinheiroPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jcbComprar)
                .addGap(155, 155, 155)
                .addComponent(jcbVender))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lbComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(lbVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jcbComprarArmas)
                .addGap(37, 37, 37)
                .addComponent(jcComprarArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jcbVenderArmas)
                .addGap(37, 37, 37)
                .addComponent(jcVenderArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jcbComprarArmaduras)
                .addGap(11, 11, 11)
                .addComponent(jcComprarArmaduras, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jcbVenderArmaduras)
                .addGap(11, 11, 11)
                .addComponent(jcVenderArmaduras, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jcbComprarEscudos)
                .addGap(29, 29, 29)
                .addComponent(jcComprarEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jcbVenderEscudos)
                .addGap(29, 29, 29)
                .addComponent(jcVenderEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jcbComprarConsumiveis)
                .addGap(3, 3, 3)
                .addComponent(jcComprarConsumiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jcbVenderConsumiveis)
                .addGap(3, 3, 3)
                .addComponent(jcVenderConsumiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlQuantComprar)
                .addGap(12, 12, 12)
                .addComponent(QuantComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jlQuantVender)
                .addGap(12, 12, 12)
                .addComponent(QuantVender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbPrecoComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251)
                .addComponent(lbPreçoVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jbComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188)
                .addComponent(jbVender, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDinheiroPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbComprar)
                    .addComponent(jcbVender))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbComprarArmas)
                    .addComponent(jcComprarArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVenderArmas)
                    .addComponent(jcVenderArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbComprarArmaduras)
                    .addComponent(jcComprarArmaduras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVenderArmaduras)
                    .addComponent(jcVenderArmaduras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbComprarEscudos)
                    .addComponent(jcComprarEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVenderEscudos)
                    .addComponent(jcVenderEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbComprarConsumiveis)
                    .addComponent(jcComprarConsumiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVenderConsumiveis)
                    .addComponent(jcVenderConsumiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlQuantComprar)
                    .addComponent(QuantComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuantVender)
                    .addComponent(QuantVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrecoComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPreçoVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVender, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jcComprarArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcComprarArmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcComprarArmasActionPerformed

    private void jbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprarActionPerformed
        int varComprar = (Integer.parseInt(QuantComprar.getText()));
        if (jcbComprarArmaduras.isSelected()) {
            PersonagensArmaduras comprar = new PersonagensArmaduras();
            comprar.getQuantidade_armadura();
            comprar.setQuantidade_armadura(varComprar);
        }
        if (jcbComprarArmas.isSelected()) {
            PersonagensArmas comprar = new PersonagensArmas();
            comprar.getQuantidade_arma();
            comprar.setQuantidade_arma(varComprar);
        }
        if (jcbComprarEscudos.isSelected()) {
            PersonagensEscudos comprar = new PersonagensEscudos();
            comprar.getQuantidade_escudo();
            comprar.setQuantidade_escudo(varComprar);
        }
        if (jcbComprarConsumiveis.isSelected()) {
            PersonagensConsumiveis comprar = new PersonagensConsumiveis();
            comprar.getQuantidade_consumivel();
            comprar.setQuantidade_consumivel(varComprar);
        }
    }//GEN-LAST:event_jbComprarActionPerformed

    private void jcbVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderActionPerformed
        if (jcbVender.isSelected()) {
            lbVender.setVisible(true);
            jcbVenderArmas.setVisible(true);
            jcbVenderConsumiveis.setVisible(true);
            jcbVenderEscudos.setVisible(true);
            jcbVenderArmaduras.setVisible(true);
        } else {
            lbVender.setVisible(false);
            jcbVenderConsumiveis.setVisible(false);
            jcbVenderEscudos.setVisible(false);
            jcbVenderArmaduras.setVisible(false);
            jcbVenderArmas.setVisible(false);
            jcVenderConsumiveis.setVisible(false);
            jcVenderEscudos.setVisible(false);
            jcVenderArmaduras.setVisible(false);
            jcVenderArmas.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
            jlQuantVender.setVisible(false);
            QuantVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderActionPerformed

    private void jcbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarActionPerformed
        if (jcbComprar.isSelected()) {
            lbComprar.setVisible(true);
            jcbComprarArmas.setVisible(true);
            jcbComprarConsumiveis.setVisible(true);
            jcbComprarEscudos.setVisible(true);
            jcbComprarArmaduras.setVisible(true);

        } else {
            lbComprar.setVisible(false);
            jcbComprarConsumiveis.setVisible(false);
            jcbComprarEscudos.setVisible(false);
            jcbComprarArmaduras.setVisible(false);
            jcbComprarArmas.setVisible(false);
            jcComprarConsumiveis.setVisible(false);
            jcComprarEscudos.setVisible(false);
            jcComprarArmaduras.setVisible(false);
            jcComprarArmas.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);      
            jlQuantComprar.setVisible(false);
            QuantComprar.setVisible(false);

        }
    }//GEN-LAST:event_jcbComprarActionPerformed

    private void jcbComprarArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarArmasActionPerformed
        if (jcbComprarArmas.isSelected()) {
            jcComprarArmas.setVisible(true);
            jbComprar.setVisible(true);
            lbPrecoComprar.setVisible(true);
            jlQuantComprar.setVisible(true);
            QuantComprar.setVisible(true);

        } else {
            jcComprarArmas.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);
            jlQuantComprar.setVisible(false);
            QuantComprar.setVisible(false);
        }
    }//GEN-LAST:event_jcbComprarArmasActionPerformed

    private void jcbComprarArmadurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarArmadurasActionPerformed
       /* try    
          {    
             
              Connection conn;    
              conn = Conexao.getConexao();//classe de conexao com banco  
              Statement st = conn.createStatement();    
              ResultSet rs = st.executeQuery("SELECT nome_armadura FROM armaduras" );    
              while(rs.next())    
              {   
                  jcComprarArmaduras.addItem(rs.getString("nome_armadura"));    
              }    
              rs.close();    
              conn.close();    
          }    
          catch(Exception e)    
          {    
              JOptionPane.showMessageDialog(null,     
                      "Ocorreu erro ao carregar a Combo Box", "Erro",    
                      JOptionPane.ERROR_MESSAGE);    
       } 
        
        */
  
        
        
        if (jcbComprarArmaduras.isSelected()) {
            jcComprarArmaduras.setVisible(true);
            jbComprar.setVisible(true);
            lbPrecoComprar.setVisible(true);
            jlQuantComprar.setVisible(true);
            QuantComprar.setVisible(true);
        } else {
            jcComprarArmaduras.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);
            jlQuantComprar.setVisible(false);
            QuantComprar.setVisible(false);
            jcComprarArmaduras.removeAllItems(); 
        }
    }//GEN-LAST:event_jcbComprarArmadurasActionPerformed

    private void jcbComprarEscudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarEscudosActionPerformed
        if (jcbComprarEscudos.isSelected()) {
            jcComprarEscudos.setVisible(true);
            jbComprar.setVisible(true);
            lbPrecoComprar.setVisible(true);
            jlQuantComprar.setVisible(true);
            QuantComprar.setVisible(true);
        } else {
            jcComprarEscudos.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);
            jlQuantComprar.setVisible(false);
            QuantComprar.setVisible(false);

        }
    }//GEN-LAST:event_jcbComprarEscudosActionPerformed

    private void jcbComprarConsumiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarConsumiveisActionPerformed
        if (jcbComprarConsumiveis.isSelected()) {
            jcComprarConsumiveis.setVisible(true);
            jbComprar.setVisible(true);
            lbPrecoComprar.setVisible(true);
            QuantComprar.setVisible(true);
        } else {
            jcComprarConsumiveis.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);
            QuantComprar.setVisible(false);
        }
    }//GEN-LAST:event_jcbComprarConsumiveisActionPerformed

    private void jcbVenderArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderArmasActionPerformed
        if (jcbVenderArmas.isSelected()) {
            jcVenderArmas.setVisible(true);
            jbVender.setVisible(true);
            lbPreçoVender.setVisible(true);
            jlQuantVender.setVisible(true);
            QuantVender.setVisible(true);
        } else {
            jcVenderArmas.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
            jlQuantVender.setVisible(false);
            QuantVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderArmasActionPerformed

    private void jcbVenderArmadurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderArmadurasActionPerformed
        if (jcbVenderArmaduras.isSelected()) {
            jcVenderArmaduras.setVisible(true);
            jbVender.setVisible(true);
            lbPreçoVender.setVisible(true);
            jlQuantVender.setVisible(true);
            QuantVender.setVisible(true);
        } else {
            jcVenderArmaduras.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
            jlQuantVender.setVisible(false);
            QuantVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderArmadurasActionPerformed

    private void jcbVenderEscudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderEscudosActionPerformed
        if (jcbVenderEscudos.isSelected()) {
            jcVenderEscudos.setVisible(true);
            jbVender.setVisible(true);
            lbPreçoVender.setVisible(true);
            jlQuantVender.setVisible(true);
            QuantVender.setVisible(true);
        } else {
            jcVenderEscudos.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
            jlQuantVender.setVisible(false);
            QuantVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderEscudosActionPerformed

    private void jcbVenderConsumiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderConsumiveisActionPerformed
        if (jcbVenderConsumiveis.isSelected()) {
            jcVenderConsumiveis.setVisible(true);
            jbVender.setVisible(true);
            lbPreçoVender.setVisible(true);
            jlQuantVender.setVisible(true);
            QuantVender.setVisible(true);
        } else {
            jcVenderConsumiveis.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
            jlQuantVender.setVisible(false);
            QuantVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderConsumiveisActionPerformed

    private void jcbComprarComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jcbComprarComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbComprarComponentHidden

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jbVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVenderActionPerformed
        int varVender = (Integer.parseInt(QuantVender.getText()));

        if (jcbVenderArmaduras.isSelected()) {
            PersonagensArmaduras vender = new PersonagensArmaduras();
            vender.setQuantidade_armadura(varVender);
        }
        if (jcbVenderArmas.isSelected()) {
            PersonagensArmas vender = new PersonagensArmas();
            vender.setQuantidade_arma(varVender);
        }
        if (jcbVenderEscudos.isSelected()) {
            PersonagensEscudos vender = new PersonagensEscudos();
            vender.setQuantidade_escudo(varVender);
        }
        if (jcbVenderConsumiveis.isSelected()) {
            PersonagensConsumiveis vender = new PersonagensConsumiveis();
            vender.setQuantidade_consumivel(varVender);
        }
    }//GEN-LAST:event_jbVenderActionPerformed

    private void QuantComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVendaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVendaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVendaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVendaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVendaItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField QuantComprar;
    private javax.swing.JTextField QuantVender;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbComprar;
    private javax.swing.JButton jbVender;
    private javax.swing.JComboBox jcComprarArmaduras;
    private javax.swing.JComboBox jcComprarArmas;
    private javax.swing.JComboBox jcComprarConsumiveis;
    private javax.swing.JComboBox jcComprarEscudos;
    private javax.swing.JComboBox jcVenderArmaduras;
    private javax.swing.JComboBox jcVenderArmas;
    private javax.swing.JComboBox jcVenderConsumiveis;
    private javax.swing.JComboBox jcVenderEscudos;
    private javax.swing.JCheckBox jcbComprar;
    private javax.swing.JCheckBox jcbComprarArmaduras;
    private javax.swing.JCheckBox jcbComprarArmas;
    private javax.swing.JCheckBox jcbComprarConsumiveis;
    private javax.swing.JCheckBox jcbComprarEscudos;
    private javax.swing.JCheckBox jcbVender;
    private javax.swing.JCheckBox jcbVenderArmaduras;
    private javax.swing.JCheckBox jcbVenderArmas;
    private javax.swing.JCheckBox jcbVenderConsumiveis;
    private javax.swing.JCheckBox jcbVenderEscudos;
    private javax.swing.JLabel jlQuantComprar;
    private javax.swing.JLabel jlQuantVender;
    private java.awt.Label label2;
    private java.awt.Label lbComprar;
    private java.awt.Label lbDinheiroPersonagem;
    private java.awt.Label lbPrecoComprar;
    private java.awt.Label lbPreçoVender;
    private java.awt.Label lbVender;
    // End of variables declaration//GEN-END:variables
}
