/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Micro10
 */
public class JFVendaItens extends javax.swing.JFrame {

    /**
     * Creates new form JFVendaItens
     */
    public JFVendaItens() {
        initComponents();
       jbComprar.setVisible(false);
        lbComprar.setVisible(false);
        lbPrecoComprar.setVisible(false);
        jcbVenderConsumiveis.setVisible(false);
        jcbVenderEscudos.setVisible(false);
        jcbVenderArmaduras.setVisible(false);
        jcbVenderArmas.setVisible(false);
        jcVenderConsumiveis.setVisible(false);
        jcVenderEscudos.setVisible(false);
        jcVenderArmaduras.setVisible(false);         //////Oculta objetos setados antes de abrir o form
        jcVenderArmas.setVisible(false);

        jbVender.setVisible(false);
        lbVender.setVisible(false);
        lbPreçoVender.setVisible(false);
        jcbComprarConsumiveis.setVisible(false);
        jcbComprarEscudos.setVisible(false);
        jcbComprarArmaduras.setVisible(false);
        jcbComprarArmas.setVisible(false);
        jcComprarConsumiveis.setVisible(false);
        jcComprarEscudos.setVisible(false);
        jcComprarArmaduras.setVisible(false);
        jcComprarArmas.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        label2 = new java.awt.Label();
        lbDinheiroPersonagem = new java.awt.Label();
        lbComprar = new java.awt.Label();
        jcComprarArmas = new javax.swing.JComboBox();
        lbVender = new java.awt.Label();
        jcVenderArmas = new javax.swing.JComboBox();
        jcComprarArmaduras = new javax.swing.JComboBox();
        jcComprarEscudos = new javax.swing.JComboBox();
        jcComprarConsumiveis = new javax.swing.JComboBox();
        jcVenderArmaduras = new javax.swing.JComboBox();
        jcVenderEscudos = new javax.swing.JComboBox();
        jcVenderConsumiveis = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lbPrecoComprar = new java.awt.Label();
        lbPreçoVender = new java.awt.Label();
        jbComprar = new javax.swing.JButton();
        jbVender = new javax.swing.JButton();
        jcbComprar = new javax.swing.JCheckBox();
        jcbVender = new javax.swing.JCheckBox();
        jcbComprarArmas = new javax.swing.JCheckBox();
        jcbComprarArmaduras = new javax.swing.JCheckBox();
        jcbComprarEscudos = new javax.swing.JCheckBox();
        jcbComprarConsumiveis = new javax.swing.JCheckBox();
        jcbVenderArmas = new javax.swing.JCheckBox();
        jcbVenderArmaduras = new javax.swing.JCheckBox();
        jcbVenderEscudos = new javax.swing.JCheckBox();
        jcbVenderConsumiveis = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Peças de Ouro Disponiveis:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(lbDinheiroPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 10, 80, -1));

        lbComprar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbComprar.setText("O que você deseja comprar?");
        getContentPane().add(lbComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jcComprarArmas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcComprarArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcComprarArmasActionPerformed(evt);
            }
        });
        getContentPane().add(jcComprarArmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 171, -1));

        lbVender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbVender.setText("O que você deseja vender?");
        getContentPane().add(lbVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jcVenderArmas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcVenderArmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 171, -1));

        jcComprarArmaduras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcComprarArmaduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 171, -1));

        jcComprarEscudos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcComprarEscudos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 171, -1));

        jcComprarConsumiveis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcComprarConsumiveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 171, -1));

        jcVenderArmaduras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcVenderArmaduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 171, -1));

        jcVenderEscudos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcVenderEscudos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 171, -1));

        jcVenderConsumiveis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcVenderConsumiveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 171, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("Olá viajante você deseja comprar ou vender itens?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        lbPrecoComprar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbPrecoComprar.setText("Preço:");
        getContentPane().add(lbPrecoComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        lbPreçoVender.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbPreçoVender.setText("Preço:");
        getContentPane().add(lbPreçoVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jbComprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbComprar.setText("Comprar");
        jbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprarActionPerformed(evt);
            }
        });
        getContentPane().add(jbComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 112, 39));

        jbVender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbVender.setText("Vender");
        jbVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVenderActionPerformed(evt);
            }
        });
        getContentPane().add(jbVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 112, 39));

        jcbComprar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprar.setText("Comprar");
        jcbComprar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jcbComprarComponentHidden(evt);
            }
        });
        jcbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarActionPerformed(evt);
            }
        });
        getContentPane().add(jcbComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jcbVender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVender.setText("Vender");
        jcbVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderActionPerformed(evt);
            }
        });
        getContentPane().add(jcbVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jcbComprarArmas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarArmas.setText("Armas");
        jcbComprarArmas.setHideActionText(true);
        jcbComprarArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarArmasActionPerformed(evt);
            }
        });
        getContentPane().add(jcbComprarArmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jcbComprarArmaduras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarArmaduras.setText("Armaduras");
        jcbComprarArmaduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarArmadurasActionPerformed(evt);
            }
        });
        getContentPane().add(jcbComprarArmaduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jcbComprarEscudos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarEscudos.setText("Escudos");
        jcbComprarEscudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarEscudosActionPerformed(evt);
            }
        });
        getContentPane().add(jcbComprarEscudos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jcbComprarConsumiveis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarConsumiveis.setText("Consumiveis");
        jcbComprarConsumiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarConsumiveisActionPerformed(evt);
            }
        });
        getContentPane().add(jcbComprarConsumiveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jcbVenderArmas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderArmas.setText("Armas");
        jcbVenderArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderArmasActionPerformed(evt);
            }
        });
        getContentPane().add(jcbVenderArmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jcbVenderArmaduras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderArmaduras.setText("Armaduras");
        jcbVenderArmaduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderArmadurasActionPerformed(evt);
            }
        });
        getContentPane().add(jcbVenderArmaduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jcbVenderEscudos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderEscudos.setText("Escudos");
        jcbVenderEscudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderEscudosActionPerformed(evt);
            }
        });
        getContentPane().add(jcbVenderEscudos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jcbVenderConsumiveis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderConsumiveis.setText("Consumiveis");
        jcbVenderConsumiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderConsumiveisActionPerformed(evt);
            }
        });
        getContentPane().add(jcbVenderConsumiveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcComprarArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcComprarArmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcComprarArmasActionPerformed

    private void jbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprarActionPerformed

    }//GEN-LAST:event_jbComprarActionPerformed

    private void jcbVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderActionPerformed
        if (jcbVender.isSelected()) {
            lbVender.setVisible(true);
            jcbVenderArmas.setVisible(true);
            jcbVenderConsumiveis.setVisible(true);
            jcbVenderEscudos.setVisible(true);
            jcbVenderArmaduras.setVisible(true);
        } else {
            lbVender.setVisible(false);
            jcbVenderConsumiveis.setVisible(false);
            jcbVenderEscudos.setVisible(false);
            jcbVenderArmaduras.setVisible(false);
            jcbVenderArmas.setVisible(false);
            jcVenderConsumiveis.setVisible(false);
            jcVenderEscudos.setVisible(false);
            jcVenderArmaduras.setVisible(false);
            jcVenderArmas.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderActionPerformed

    private void jcbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarActionPerformed
        if (jcbComprar.isSelected()) {
            lbComprar.setVisible(true);
            jcbComprarArmas.setVisible(true);
            jcbComprarConsumiveis.setVisible(true);
            jcbComprarEscudos.setVisible(true);
            jcbComprarArmaduras.setVisible(true);

        } else {
            lbComprar.setVisible(false);
            jcbComprarConsumiveis.setVisible(false);
            jcbComprarEscudos.setVisible(false);
            jcbComprarArmaduras.setVisible(false);
            jcbComprarArmas.setVisible(false);
            jcComprarConsumiveis.setVisible(false);
            jcComprarEscudos.setVisible(false);
            jcComprarArmaduras.setVisible(false);
            jcComprarArmas.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);

        }
    }//GEN-LAST:event_jcbComprarActionPerformed

    private void jcbComprarArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarArmasActionPerformed
        if (jcbComprarArmas.isSelected()) {
            jcComprarArmas.setVisible(true);
            jbComprar.setVisible(true);
            lbPrecoComprar.setVisible(true);
        } else {
            jcComprarArmas.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);
        }
    }//GEN-LAST:event_jcbComprarArmasActionPerformed

    private void jcbComprarArmadurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarArmadurasActionPerformed
        if (jcbComprarArmaduras.isSelected()) {
            jcComprarArmaduras.setVisible(true);
            jbComprar.setVisible(true);
            lbPrecoComprar.setVisible(true);
        } else {
            jcComprarArmaduras.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);
        }
    }//GEN-LAST:event_jcbComprarArmadurasActionPerformed

    private void jcbComprarEscudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarEscudosActionPerformed
        if (jcbComprarEscudos.isSelected()) {
            jcComprarEscudos.setVisible(true);
            jbComprar.setVisible(true);
            lbPrecoComprar.setVisible(true);
        } else {
            jcComprarEscudos.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);

        }
    }//GEN-LAST:event_jcbComprarEscudosActionPerformed

    private void jcbComprarConsumiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarConsumiveisActionPerformed
        if (jcbComprarConsumiveis.isSelected()) {
            jcComprarConsumiveis.setVisible(true);
            jbComprar.setVisible(true);
            lbPrecoComprar.setVisible(true);
        } else {
            jcComprarConsumiveis.setVisible(false);
            jbComprar.setVisible(false);
            lbPrecoComprar.setVisible(false);
        }
    }//GEN-LAST:event_jcbComprarConsumiveisActionPerformed

    private void jcbVenderArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderArmasActionPerformed
        if (jcbVenderArmas.isSelected()) {
            jcVenderArmas.setVisible(true);
            jbVender.setVisible(true);
            lbPreçoVender.setVisible(true);
        } else {
            jcVenderArmas.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderArmasActionPerformed

    private void jcbVenderArmadurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderArmadurasActionPerformed
        if (jcbVenderArmaduras.isSelected()) {
            jcVenderArmaduras.setVisible(true);
            jbVender.setVisible(true);
            lbPreçoVender.setVisible(true);
        } else {
            jcVenderArmaduras.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderArmadurasActionPerformed

    private void jcbVenderEscudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderEscudosActionPerformed
        if (jcbVenderEscudos.isSelected()) {
            jcVenderEscudos.setVisible(true);
            jbVender.setVisible(true);
            lbPreçoVender.setVisible(true);
        } else {
            jcVenderEscudos.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderEscudosActionPerformed

    private void jcbVenderConsumiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderConsumiveisActionPerformed
        if (jcbVenderConsumiveis.isSelected()) {
            jcVenderConsumiveis.setVisible(true);
            jbVender.setVisible(true);
            lbPreçoVender.setVisible(true);
        } else {
            jcVenderConsumiveis.setVisible(false);
            jbVender.setVisible(false);
            lbPreçoVender.setVisible(false);
        }
    }//GEN-LAST:event_jcbVenderConsumiveisActionPerformed

    private void jcbComprarComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jcbComprarComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbComprarComponentHidden

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jbVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVendaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVendaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVendaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVendaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVendaItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbComprar;
    private javax.swing.JButton jbVender;
    private javax.swing.JComboBox jcComprarArmaduras;
    private javax.swing.JComboBox jcComprarArmas;
    private javax.swing.JComboBox jcComprarConsumiveis;
    private javax.swing.JComboBox jcComprarEscudos;
    private javax.swing.JComboBox jcVenderArmaduras;
    private javax.swing.JComboBox jcVenderArmas;
    private javax.swing.JComboBox jcVenderConsumiveis;
    private javax.swing.JComboBox jcVenderEscudos;
    private javax.swing.JCheckBox jcbComprar;
    private javax.swing.JCheckBox jcbComprarArmaduras;
    private javax.swing.JCheckBox jcbComprarArmas;
    private javax.swing.JCheckBox jcbComprarConsumiveis;
    private javax.swing.JCheckBox jcbComprarEscudos;
    private javax.swing.JCheckBox jcbVender;
    private javax.swing.JCheckBox jcbVenderArmaduras;
    private javax.swing.JCheckBox jcbVenderArmas;
    private javax.swing.JCheckBox jcbVenderConsumiveis;
    private javax.swing.JCheckBox jcbVenderEscudos;
    private java.awt.Label label2;
    private java.awt.Label lbComprar;
    private java.awt.Label lbDinheiroPersonagem;
    private java.awt.Label lbPrecoComprar;
    private java.awt.Label lbPreçoVender;
    private java.awt.Label lbVender;
    // End of variables declaration//GEN-END:variables
}
